[features]
seeds = false
skip-lint = false

[programs.localnet]
monopoly_game = "8HvezzN7yPPPNri1pjPzsM79YtevVFGwV66FWNsaoP1U"

[programs.devnet]
monopoly_game = "8HvezzN7yPPPNri1pjPzsM79YtevVFGwV66FWNsaoP1U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
